In [45]:
import numpy as np
from sklearn.cluster import KMeans
from skimage import io
import sys

In [53]:
# Load image
image = io.imread("./input_images/koala.jpeg")
rows, cols = image.shape[0], image.shape[1]

# Flatten the image, represent it as 3-arrays of [R, G, B]
image = np.array(image.reshape(rows * cols, 3))

50451
Original size: 151353
144 bytes


In [54]:
km = KMeans(n_clusters=int(input("Number of colours (value of k):")))
labels = km.fit_predict(image)
centroids = km.cluster_centers_

for i in range(len(labels)):
    # pixel in image = image[i]
    new_colour = centroids[labels[i]]

    # Assign one of the k colours to the pixel
    image[i] = new_colour

[[117.7136322  113.75480329 105.14547118]
 [178.23305785 176.30826446 172.84876033]
 [ 57.61053985  51.70308483  40.79434447]
 [250.32357043 250.59274756 251.48117155]
 [136.69277108 157.23975904 111.97831325]
 [ 93.11087866 115.05020921  69.34205021]
 [ 33.17784257  25.5335277   16.54081633]
 [ 97.98212512  94.48460775  83.23038729]
 [108.94425087  77.45180023  58.73519164]
 [205.90093708 204.25568942 205.63721553]
 [113.74488802 137.58227848  90.44498539]
 [154.19512195 150.94906743 143.91750359]
 [189.94100295 200.8820059  150.16224189]
 [ 68.47741935  62.82967742  51.37419355]
 [135.68965517 131.83579639 124.56239737]
 [170.36820084 185.44142259 129.62761506]
 [221.81773399 243.01477833 160.4679803 ]
 [104.51928504 126.38758231  80.42709313]
 [187.28746929 195.86977887 172.10810811]
 [156.58576052 117.33009709 103.66666667]
 [167.97584973 167.27370304 165.01341682]
 [ 84.21011673 102.3618677   70.307393  ]
 [160.3968254  189.20899471 100.8968254 ]
 [  9.51617251   4.15363881   1.91

In [48]:
# Unflatten the image back to its original shape, and transform the ith pixel to the ith label.
image = image.reshape(rows, cols, 3)
print(image.shape)

# Save image to output
io.imsave("./output_images/koala.jpeg", image)

# todo: there are a lot of repeated values in the image array, so use an algorithm like run length encoding to reduce the size!
# todo: do the same thing but with a kmeans algorithm from scratch

(251, 201, 3)
